version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: slbb
    container_name: slbb-app
    restart: always
    working_dir: /var/www
    volumes:
      - sqlite_data:/var/www/database
      - public_build:/var/www/public/build
    networks:
      - app-net

  webserver:
    image: nginx:alpine
    container_name: slbb-webserver
    restart: always
    ports:
      - "8800:80"
    volumes:
      - .:/var/www
      - public_build:/var/www/public/build
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - app-net
    depends_on:
      - app

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_HEADER=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  bot-control:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    image: slbb-bot
    container_name: slbb-bot-control
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegram_bot:/app
    networks:
      - app-net
    depends_on:
      - app

networks:
  app-net:
    driver: bridge

volumes:
  sqlite_data:
    driver: local
  public_build:
    driver: local